Gemfile
Gemfile.lock
config/unicorn.rb

本番環境にデプロイするための記述
本番環境にデプロイするために必要であるから

[WIP] 本番環境にデプロイ

---

Capfile
Gemfile.lock
config/deploy.rb
config/deploy/production.rb
config/deploy/staging.rb
config/unicorn.rb

capistranoを使って自動デプロイするための記述
capistranoを使って自動デプロイするのに必要な記述であるから。

capistranoの導入

---

app/controllers/application_controller.rb
config/deploy.rb
config/deploy/production.rb

本番環境でBasic認証をかけるための記述
本番環境でBasic認証をするにおいて、必要な記述であるから

Basic_authentication

---

README.md

メルカリのデータベース設計、及びER図作成
#WHY
メルカリのコピーアプリを作成するにあたって必要な為

database-design

---

app/assets/stylesheets/mypages.scss
app/controllers/mypages_controller.rb
app/helpers/mypages_helper.rb
app/views/mypages/edit.html.haml
app/views/mypages/index.html.haml
app/views/mypages/update.html.haml
config/routes.rb
spec/controllers/mypages_controller_spec.rb
spec/helpers/mypages_helper_spec.rb
spec/views/mypages/edit.html.haml_spec.rb
spec/views/mypages/index.html.haml_spec.rb
spec/views/mypages/update.html.haml_spec.rb

#What
メルカリのクローン作成におけるプロフィール編集ページのビュー作成
メルカリのクローン作成に必要なページであるから

[WIP]プロフィール編集ページのビュー作成

---

app/assets/stylesheets/_footer.scss
app/views/shared/_footer.html.haml

footerのビューを修正

---

app/assets/stylesheets/_exhibit.scss
app/assets/stylesheets/application.scss
app/controllers/products_controller.rb
app/views/products/exhibit.html.haml
config/routes.rb

商品出品画面の実装
商品編集、商品削除の実装の際にビューがあると実装しやすいため
https://gyazo.com/b3e9c264aff345a9ee6b0f8e72652ca7

Item exhibit

---

app/controllers/products_controller.rb
config/routes.rb

商品削除の実装
出品した商品を削除するのは必須機能であるから

Item destroy

---

spec/models/product_spec.rb

削除機能実装（単体テストの実装）

---

app/assets/stylesheets/_mypage-header.scss
app/views/layouts/_breadcrumbs.html.haml
app/views/mypages/card.html.haml
app/views/mypages/edit.html.haml
app/views/mypages/identification.html.haml
app/views/mypages/index.html.haml
app/views/products/exhibit.html.haml
app/views/shared/_credits.html.haml
app/views/shared/_mypage-header.html.haml
app/views/users/logout.html.haml
config/breadcrumbs.rb

ユーザーが今WEBサイト内のどの位置にいるのかを視覚的に分かりやすくするため、上位の階層となるWEBページを階層順にリストアップしてリンクを設置したリスト
メルカリのクローン作成において必須の機能であるから。

パンくずリスト機能の実装

---

app/assets/stylesheets/_mypage-header.scss
app/assets/stylesheets/_sell.scss
app/controllers/products_controller.rb
app/views/layouts/_breadcrumbs.html.haml
app/views/mypages/card.html.haml
app/views/mypages/edit.html.haml
app/views/mypages/identification.html.haml
app/views/mypages/index.html.haml
app/views/products/exhibit.html.haml
app/views/products/new.html.haml
app/views/shared/_credits.html.haml
app/views/shared/_mypage-header.html.haml
app/views/users/logout.html.haml
config/breadcrumbs.rb

オプションタグの値を送信できるようにした。あと、これまでの実装の微調整、修正も行なった。
ビューの崩れやフォームが当たってないビューなどがあるため。

オプションタグの値を送信＆微調整・修正

---

app/views/devise/registrations/_rg-header.html.haml
app/views/devise/sessions/_header.html.haml
app/views/products/buying.html.haml
app/views/products/new.html.haml
app/views/shared/_header.html.haml
app/views/shared/_mypage-header.html.haml

メルカリのロゴをクリックすることでルートパス（トップページ）へ飛ぶ実装
メルカリのロゴをクリックすることでルートパス（トップページ）へ飛ベば便利であるから

Click to rootpath

---

app/assets/stylesheets/_exhibit.scss
app/controllers/products_controller.rb
app/views/products/exhibit.html.haml
app/views/products/sell.html.haml

Details-product

---

.gitignore
Gemfile
Gemfile.lock
app/assets/stylesheets/_index.scss
app/assets/stylesheets/_products-list.scss
app/assets/stylesheets/application.scss
app/controllers/products_controller.rb
app/views/products/index.html.haml
app/views/products/show.html.haml
app/views/shared/_products-brand.html.haml
app/views/shared/_products-category.html.haml
db/schema.rb
spec/controllers/products_controller_spec.rb
spec/factories/products.rb

登録した商品一覧をトップページに表示する
#WHY
必要な機能の為。
https://gyazo.com/f14690332253b107a85477d98e98b98f

[WIP]商品一覧表示

---

app/views/shared/_sidebar.html.haml

CSSの微調整や細かい修正
本物のメルカリとデザインが異なるため

CSSの微調整や細かい修正

---

app/assets/stylesheets/_edit-item.scss
app/assets/stylesheets/_exhibit.scss
app/assets/stylesheets/_products-list.scss
app/assets/stylesheets/application.scss
app/controllers/mypages_controller.rb
app/controllers/products_controller.rb
app/views/mypages/products_list.html.haml
app/views/products/edit.html.haml
app/views/products/exhibit.html.haml
app/views/shared/_details-header.html.haml
app/views/shared/_mypage-header.html.haml
app/views/shared/_sidebar.html.haml
config/routes.rb
db/schema.rb

本物のメルカリと同様の編集機能を実装する。
必須機能のため。

商品情報編集機能の実装

---

app/views/shared/_header.html.haml
app/views/shared/_sidebar.html.haml

サイドバーのリンクの更新(出品する、プロフィール、本人情報）
URL打ち込みのままだと不便であるから

Link update (sidebar)

---

app/controllers/products_controller.rb
app/views/products/index.html.haml

売り手以外は編集、削除、更新をできなくする。
売り手以外が編集、削除、更新ができてしまったらいけないから。

Ensure correct user

---

app/views/shared/_header.html.haml

ログインによる条件分岐（トップページのヘッダーのビュー）
ログインしていない状態ではマイページに飛べないようにする、また、ログインしていない場合は新規登録、ログインのビューを表示させる。

Conditional branch by login

---

app/views/shared/_sidebar.html.haml

Update Sidebar link

---

app/assets/javascripts/slick.js
app/assets/stylesheets/_item-details.scss
app/assets/stylesheets/_slick.scss
app/assets/stylesheets/application.scss
app/controllers/products_controller.rb
app/views/layouts/application.html.haml
app/views/products/_details.html.haml

商品詳細ページのメイン画像（一番大きい画像）の下に関連画像を複数、表示できるようにする。
画像が一枚しか表示できないようになっているため。

商品詳細ページで複数の画像を表示できるようにする。

---

app/controllers/mypages_controller.rb

products_listページで自分が出品した商品のみ表示させる。
products_listページ(出品した商品一覧ページ)で自分が出品した商品以外も表示されるため。

products_listページでログインしているユーザが出品した商品のみ表示させる。

---

app/assets/stylesheets/_exhibit.scss
app/assets/stylesheets/_sold.scss
app/assets/stylesheets/application.scss
app/controllers/products_controller.rb
app/views/products/_details.html.haml
app/views/products/_exhibit.html.haml
app/views/shared/_sold.html.haml

購入された商品にsold out の表記を出して、買えないようにする。
購入された在庫のない商品を買えるのは不自然なため。

購入された商品を購入できないようにする。

---

app/controllers/products_controller.rb
app/views/products/comfirm.html.haml

自分が出品した商品をコントローラの設定により買えないようにする。
自分の商品を買えてしまうと機能的におかしいから。
https://gyazo.com/fe0efa873b34e1f92b995120d12d30ea

自分が出品した商品は購入できないようにする

---

app/assets/stylesheets/_edit.scss
app/assets/stylesheets/_exhibit.scss
app/assets/stylesheets/_sell.scss
app/views/products/edit.html.haml
app/views/products/new.html.haml

編集ページのビューの修正

---

app/controllers/products_controller.rb
app/views/products/index.html.haml

支払いボタンで購入はできないようになっていたが、購入画面にはURL直接入力でいけてしまっている。
購入画面にいけるのはおかしいから。

自分が出品した商品の場合は、購入ページそのものにいけないようにする。一度購入した商品は購入できないようにする。

---

app/assets/javascripts/new.js
app/assets/stylesheets/_sell.scss
app/controllers/products_controller.rb
app/models/product.rb
app/views/products/_exhibit.html.haml
app/views/products/edit.html.haml
app/views/products/new.html.haml
db/schema.rb

出品機能、編集機能の修正
accepts_nested_attributes_forの使い方が間違っていたため

 商品編集画面、出品画面の調整

---

app/controllers/products_controller.rb
app/views/products/edit.html.haml

編集画面で画像を新たに追加できないので追加できるようにする。
必要な機能のため

編集画面で画像を追加できるようにする。

---

app/assets/stylesheets/_sell.scss
app/views/products/new.html.haml

inputクラスをdisplay: noneで非表示にする。
表示する必要がないため。

商品出品画面と編集画面の調整

---

app/controllers/products_controller.rb

出品時に画像なしだと出品できてしまうので、できないようにする。また、そのほかの必須項目で入力漏れがある場合もできないようにする。
画像入力は必須であるため

出品時に記入漏れがあると出品できないようにする。
